apiVersion: v2
name: spliit
description: A Helm chart for deploying the Spliit app
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
